{ config, pkgs, ... }@inputs:
let
  update-soulsync-script = pkgs.writeShellScriptBin "update-soulsync" ''
    #!/usr/bin/env bash
    set -euo pipefail

    echo "Pulling latest soulsync image..."
    pull_output=$(docker pull ${config.virtualisation.oci-containers.containers."soulsync-webui".image} 2>&1)

    if echo "$pull_output" | grep -q "Downloaded"; then
      echo "New image pulled. Restarting soulsync container..."
      systemctl stop docker-soulsync-webui.service
      systemctl start docker-soulsync-webui.service
      echo "Soulsync update complete."
    else
      echo "Image already up to date. No restart needed."
    fi
  '';
in
{
  # START Auto-generated by compose2nix
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."soulsync-webui" = {
    image = "ghcr.io/nezreka/soulsync:latest";
    environment = {
      "PUID" = "${toString (config.users.users.music.uid)}";
      "PGID" = "${toString (config.users.groups.media.gid)}";
      "FLASK_ENV" = "production";
      "PYTHONPATH" = "/app";
      "SOULSYNC_CONFIG_PATH" = "/app/config/config.json";
      "TZ" = "America/New_York";
      "UMASK" = "022";
    };
    volumes = [
      "/var/lib/soulsync/MusicVideos:/app/MusicVideos:rw"
      "/var/lib/soulsync/Staging:/app/Staging:rw"
      "/var/lib/soulsync/config:/app/config:rw"
      "/var/lib/slskd/downloads:/app/downloads:rw"
      "/var/log/soulsync:/app/logs:rw"
      "/var/lib/soulsync/scripts:/app/scripts:rw"
      "soulsync_soulsync_database:/app/data:rw"
      "/mnt/media/soulsync:/app/Transfer:rw"
    ];
    ports = [
      "8008:8008/tcp"
      "8888:8888/tcp"
      "8889:8889/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--add-host=host.docker.internal:host-gateway"
      "--cpus=2"
      "--health-cmd=[\"curl\", \"-f\", \"http://localhost:8008/\"]"
      "--health-interval=30s"
      "--health-retries=3"
      "--health-start-period=1m0s"
      "--health-timeout=10s"
      "--memory-reservation=536870912b"
      "--memory=2147483648b"
      "--network-alias=soulsync"
      "--network=soulsync-network"
    ];
  };
  systemd.services."docker-soulsync-webui" = {
    serviceConfig = {
      Restart = inputs.lib.mkOverride 90 "always";
      RestartMaxDelaySec = inputs.lib.mkOverride 90 "1m";
      RestartSec = inputs.lib.mkOverride 90 "100ms";
      RestartSteps = inputs.lib.mkOverride 90 9;
    };
    after = [
      "docker-network-soulsync-network.service"
      "docker-volume-soulsync_soulsync_database.service"
    ];
    requires = [
      "docker-network-soulsync-network.service"
      "docker-volume-soulsync_soulsync_database.service"
    ];
    partOf = [
      "docker-compose-soulsync-root.target"
    ];
    wantedBy = [
      "docker-compose-soulsync-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-soulsync-network" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f soulsync-network";
    };
    script = ''
      docker network inspect soulsync-network || docker network create soulsync-network
    '';
    partOf = [ "docker-compose-soulsync-root.target" ];
    wantedBy = [ "docker-compose-soulsync-root.target" ];
  };

  # Volumes
  systemd.services."docker-volume-soulsync_soulsync_database" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect soulsync_soulsync_database || docker volume create soulsync_soulsync_database --driver=local
    '';
    partOf = [ "docker-compose-soulsync-root.target" ];
    wantedBy = [ "docker-compose-soulsync-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-soulsync-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
  # END Auto-generated by compose2nix
  environment.systemPackages = [ update-soulsync-script ];
  systemd.timers.update-soulsync = {
    description = "Update soulsync container image and restart the service.";
    timerConfig = {
      OnCalendar = "daily 03:00";
      Persistent = true;
    };
    wantedBy = [ "timers.target" ];
  };
  systemd.services.update-soulsync = {
    description = "Update soulsync container image and restart the service.";
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      ExecStart = "${update-soulsync-script}/bin/update-soulsync";
    };
  };
  services.caddy.virtualHosts = (inputs.virtualHosts.mkLocalVirtualHost "soulsync" 8008);
}
