keys:
  - &users
    - &judah age12tm8764kmufjt955lxc762ujf3mr8ms9mdfjlufj2t47suugu3jshftm4g
  - &hosts
    - &p15 age1us5c7c994fjc7mfl0xa3gqjavjeujs5j7saapg3fgvugy9eq3srsd4craq
    - &hs age1clck3zkmagrkma0q9am4e5ue02j97fzs3c9fk2zpzegpejsm9u9sdvmqn2
    - &v14 age15qhmlmndjj7e5w2e7l8efghce9aysr3k2xxac07v3yy67mkq7yes42xjay
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *judah
          - *p15
          - *hs
          - *v14