keys:
  - &users
    - &judah age12tm8764kmufjt955lxc762ujf3mr8ms9mdfjlufj2t47suugu3jshftm4g
  - &hosts
    - &p15 age1us5c7c994fjc7mfl0xa3gqjavjeujs5j7saapg3fgvugy9eq3srsd4craq
    - &hs age1chfc4w3kd4y782asmkgkev2audygd58pflm3vx9rtfzgmjyh55ushwd7e7
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *judah
          - *p15
          - *hs
