keys:
  - &users
    - &judah age12tm8764kmufjt955lxc762ujf3mr8ms9mdfjlufj2t47suugu3jshftm4g
  - &hosts
    - &p15 age1us5c7c994fjc7mfl0xa3gqjavjeujs5j7saapg3fgvugy9eq3srsd4craq
    - &hs age1yqeays30qpan9t5m4ajk3hm4rhhkqhyy9jjw04957tpzm2pwupwsz8945q
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *judah
          - *p15
          - *hs
