name: "Flake.lock: update Nix dependencies"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *" # daily at 01:00 est
  push:
    paths:
      - 'flake.nix'
    branches:
      - main

jobs:
  nix-flake-update:
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    runs-on: [nixos]
    outputs:
      pr-number: ${{ steps.create-pr.outputs.pull-request-number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Update flake.lock
        id: update
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          nix flake update --accept-flake-config --commit-lock-file

          # Capture the commit message that was generated
          {
            echo 'message<<EOF'
            git log -1 --pretty=%B
            echo 'EOF'
          } >> $GITHUB_OUTPUT

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.FLAKE_TOKEN }}
          commit-message: ${{ steps.update.outputs.message }}
          title: "Update flake inputs"
          body: |
            ${{ steps.update.outputs.message }}
          labels: |
            dependencies
            automated
          branch: update_flake_lock_action
          committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>

  build:
    needs: nix-flake-update
    runs-on: [nixos]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build with om ci
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          set -euo pipefail
          nix run github:juspay/omnix -- ci run -- --accept-flake-config

  merge:
    needs: [nix-flake-update, build]
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: auto-merge
        if: needs.nix-flake-update.outputs.pr-number != ''
        run: gh pr merge --auto --squash ${{ needs.nix-flake-update.outputs.pr-number }}
        env:
          GH_TOKEN: ${{ secrets.FLAKE_TOKEN }}
